### ISSUE TITLE
Weak Cryptography

### ISSUE THREAD

**Issue by xsuperbug** [eurialo/verbena#1]
hi,

I think, You should use a cryptographic function such as http://php.net/manual/en/function.openssl-random-pseudo-bytes.php 

https://github.com/eurialo/verbena/blob/master/bootstrap/components/security.php#L113

**Comment by ociredefz** [comment]
Hi Superbug,

I don't think It's very important to use the `openssl_random_pseudo_bytes()` function in the generation of the CSRF token name. However, I will assess if your suggestion will be in the next update.
I would be very happy in a collaboration in the framework development. 
Contact me for any questions.

Thanks for the time you spent in the code review!

Regards,
Federico
